import type { Metadata } from 'next'
import './index.css'
import '@/styles/var.css'
import '@/styles/tailwind.css'
import '@/styles/tailwindBase.css'
import { SLFC } from 'react'
import { NextIntlClientProvider } from 'next-intl'
import getI18nConfig from '@/i18n'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: SLFC = async props => {
  const locale = props.params.locale
  const { messages } = await getI18nConfig({ locale })

  return (
    <html lang="en">
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {props.children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}

export default RootLayout
