import type { Metadata } from 'next'
import './index.css'
import '@/styles/var.css'
import '@/styles/tailwind.css'
import '@/styles/tailwindBase.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
